name: Build the website from scraped data

on:
  push:
    branches:
      - 'scrape'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Build the static files
        run: |
          bun install
          bun run build

      - name: Push changes to "build" branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b build
          git add .
          git commit -m "built at $(date +"%Y.%m.%d")"
          git push -f origin build

