name: Rebuild with fresh data

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # every day at 4am
    - cron: 0 4 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Generate the JSON files and the site
        run: bun run generate

      - name: Build the website
        run: bun run build

      - name: Remove dist/ from .gitignore
        run: sed -i '/^dist\/$/d' .gitignore

      - name: Push changes to "build" branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b build 
          git add .
          git commit -m "built at $(date +"%Y.%m.%d")"
          git push -f origin build

