name: Web scrape and regenerate the data sources

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Scrape the BC Liquor store and generate the JSON files
        run: |
          bun run generate

      - name: Push changes to "scrape" branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b scrape
          git add .
          git commit -m "scraped at $(date +"%Y.%m.%d")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin scrape

